
version: '3.9'

services:
  de-pg-cr-af:
    image: cr.yandex/crp1r8pht0n0gl25aug1/de-final-prj:latest
    ports:
      - 8280:8280
      - 8998:8998
      - 15432:5432
    volumes:
    #  - st5projectpostressql:/var/lib/postgresql
      - ${AIRFLOW_DAGS_DIR:-./src/dags}:/lessons/dags
    #environment:
    #  AIRFLOW_VAR_EXAMPLE_STG_DDL_FILES_PATH: "/lessons/dags/examples/stg/init_schema_dag/ddl"
    #restart: unless-stopped

#volumes:
#  st5projectpostressql:
